### ISSUE TITLE
Android 4.3.1 support

### ISSUE THREAD

**Issue by AlfaOmega33** [jonan/ForkHub#230]
Hi! Is possible add an ability to work on Android 4.3.1 and on corresponding CyanogenMod/Replicant OS versions??

**Comment by jonan** [comment]
I increased the requirements because some external libraries started causing problems with old Android versions, and I'm not able to test them all. But you should be able to change the `minSdkVersion` here https://github.com/jonan/ForkHub/blob/master/app/build.gradle#L14 and compile it yourself, or download it from the Play Store, that still has an older version available for old devices.

**Comment by AlfaOmega33** [comment]
Ok, thank you!
