### ISSUE TITLE
Some links appear to open in forkhub then immediately instead in chrome

### ISSUE THREAD

**Issue by aphirst** [jonan/ForkHub#308]
Example: https://github.com/libass/libass/pull/236/commits/7d73cfea6590a0dbff29d837e8b621c8ed03335f
This happens when selecting this link from, say, atomic.

I don't recall seeing anything saying that forkhub can't view pull requests but it's entirely possible I've missed a part of documentation somewhere, not could I find anything in the open issues, though in part due to not knowing which key words were most relevant.

Please don't hesitate to ask for any further info if needed, or respectively discard the issue if it turns out to be known already. Thanks!

```
https://github.com/libass/libass/pull/236/commits/7d73cfea6590a0dbff29d837e8b621c8ed03335f
```

**Comment by aphirst** [comment]
Well, after this link has been parsed and reformatted by forkhub here in the issues tracker, clicking it takes me to the expected page within forkhub. I suppose that means the issue must be somewhere else, but I've double checked that, e.g., forkhub definitely had all the default associations it should.

I'd appreciate and further advice on how to debug this, and in the meantime I'll try to see whether this behaviour depends on from which application I click the link...

**Comment by jonan** [comment]
ForkHub tries to open all `http://github.com` links, but when it can't open one (not supported or not recognized), it opens it in the browser.

The problem here is that ForkHub recognizes `https://github.com/libass/libass/commit/7d73cfea6590a0dbff29d837e8b621c8ed03335f` but doesn't recognize `https://github.com/libass/libass/pull/236/commits/7d73cfea6590a0dbff29d837e8b621c8ed03335f`.

It shouldn't be hard to fix.

For further reference #93
