### ISSUE TITLE
Providing an updated changelog

### ISSUE THREAD

**Issue by Cqoicebordel** [jonan/ForkHub#42]
I have no idea what changed between versions in the last 6 months.
The commits in github doesn't seems to be much helpful, and https://github.com/jonan/ForkHub/blob/master/CHANGELOG.md didn't change for quite a while.

So, an updated file, or the correct section in the Play Store should be filled.

**Comment by jonan** [comment]
ForkHub is only 4 months old, and I haven't created an official release yet because I intended to merge my changes back to the official app. That's why all the changes are marked as `unreleased` in the [CHANGELOG](https://github.com/jonan/ForkHub/blob/master/CHANGELOG.md).

Unfortunately merging changes back doesn't seem to be possible, so I plan on creating the first official release of ForkHub this week. After that, all the releases will be tagged and the changelog will be more precise.

**Comment by Cqoicebordel** [comment]
Great !

I wasn't aware of how old ForkHub was. 
And seeing changes as unreleased while there were releases on the Play Store was weird.
Now I understand :)
