### ISSUE TITLE
404 when changing code to specific tag

### ISSUE THREAD

**Issue by danez** [jonan/ForkHub#71]
When I try to select a specific tag in the code view, for some repositories this triggers a toast saying "Not Found (404)". For example https://github.com/symfony/MonologBundle: Some newer tags work, but some older (v2.0.7) trigger a 404.

**Comment by jonan** [comment]
This looks like a bug in the API.

If you go to the [tag's page](https://github.com/symfony/MonologBundle/releases/tag/v2.0.7) you can see that the hash is [e08148c](https://github.com/symfony/MonologBundle/commit/e08148c3f4e9ef4e887891aa83f2ff65e83cfe44), but the [API](https://api.github.com/repos/symfony/MonologBundle/git/refs/tags) says that the hash is [d1b43f4](https://github.com/symfony/MonologBundle/commit/d1b43f4e54d34266707967a4c56bed072f4fe8c4), which doesn't exist.

Anyhow, I think I can fix this by referencing the actual tag name instead of the hash, I'll take a look.

**Comment by danez** [comment]
I think d1b43f4e54d34266707967a4c56bed072f4fe8c4 is not the hash of a commit but the hash of the tag. The tag itself seems to link to the commit: https://api.github.com/repos/symfony/MonologBundle/git/tags/d1b43f4e54d34266707967a4c56bed072f4fe8c4

**Comment by jonan** [comment]
You are right, when the object type is `tag` instead of `commit` the hash is not a valid commit.

I'll look into it. Thanks!

**Comment by jonan** [comment]
So the problem was that those tags where in fact annotated tags, and they weren't treated accordingly.

It's fixed now :wink:
